name: Examples Validation

on:
  push:
    branches: [ master, main, develop ]
  pull_request:
    branches: [ master, main, develop ]

jobs:
  validate-examples:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-asyncio
        pip install aiohttp || echo "aiohttp not available, examples will use fallback"

    - name: Run core functionality validation
      run: python .github/scripts/validate_examples.py

    - name: Validate SpoonOS submodule structure
      run: |
        echo "Validating SpoonOS submodule..."
        test -d spoonos || (echo "SpoonOS submodule missing" && exit 1)
        test -f spoonos/README.md || (echo "SpoonOS README missing" && exit 1)
        test -d spoonos/spoon_ai || (echo "SpoonOS core missing" && exit 1)
        echo "✅ SpoonOS submodule structure validated"

    - name: Performance test
      run: python .github/scripts/performance_test.py