name: Submodule Sync and Validation

on:
  push:
    branches: [ master, main, develop ]
  pull_request:
    branches: [ master, main, develop ]

jobs:
  submodule-validation:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Validate submodule status
      run: |
        echo "=== Submodule Status Check ==="
        git submodule status
        
        if [ ! -d "spoonos" ]; then
          echo "❌ SpoonOS submodule directory missing"
          exit 1
        fi
        
        if [ ! -f "spoonos/README.md" ]; then
          echo "❌ SpoonOS submodule appears incomplete"
          exit 1
        fi
        
        echo "✅ Submodule structure validated"

    - name: Test integration with current submodule
      run: |
        export PYTHONPATH="${PYTHONPATH}:$(pwd)/src"
        python -c "
        import sys
        sys.path.insert(0, 'src')
        from spoon_integration import SPOON_AVAILABLE
        print(f'SpoonOS integration status: {SPOON_AVAILABLE}')
        
        import os
        print(f'SpoonOS path exists: {os.path.exists(\"spoonos\")}')
        print('✅ Integration test with current submodule passed')
        "