name: Working CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: true
        
    - name: Setup Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: 3.11
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install cryptography
        
    - name: Show environment
      run: |
        pwd
        ls -la
        python --version
        
    - name: Test our code
      run: |
        cd src
        python -c "import sys; sys.path.insert(0, '.'); import tee_wallet; print('✓ tee_wallet imported'); import spoon_integration; print('✓ spoon_integration imported')"
        
    - name: Validate structure
      run: |
        test -f src/tee_wallet.py && echo "✓ tee_wallet.py found"
        test -f src/spoon_integration.py && echo "✓ spoon_integration.py found"
        test -d spoonos && echo "✓ spoonos submodule found" || echo "⚠ spoonos submodule missing (expected)"
        echo "✓ Project structure validated"